export const jobFairs = [
  {
    sCRMEmpCount: '2',
    sCRMEmpNames: 'Parmes diamonds exp pvt ltd., DECENT MANPOWER',
    id: 'CMP-06688-F9B2W7',
    title:
      'JF-GJ-Online ONLINE JOB FAIR on NCS Portal from 30th Jul\u002720 to 5th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'NOTE- You will be contacted telepathically by the employer when the selection process will be conducted by that employer.',
    color: '#5cb85c',
    eventType: 'J',
    start: '/Date(1596047400000)/',
    end: '/Date(1596652140000)/',
    regStDate: '/Date(1595442600000)/',
    regEnDate: '/Date(1595960940000)/',
    eventMode: true,
    OrganisedBy: 'Navsari, Gujarat',
  },
  {
    sCRMEmpCount: '4',
    sCRMEmpNames:
      '1-Xzent aqua pvt Ltd , 2- Vinthuna Fertilizers , 3-Kalyani Solar Power , 4-Scorpix India',
    id: 'CMP-06708-L1P8H9',
    title:
      'JF-UP-Online ROJGAR MELA on NCS Portal from 31st Jul\u002720 to 5th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '2',
    totalJobseekers: '140',
    totalParticipants: '142',
    totalJobs: '3',
    eventDesc:
      '1.Number of expected 04 Companies 2.Prominent 04 Companies expected 3.Agriculture and Related,Wholesale and Retail and Other Service Activities 4.Number of expected 317 vacancies 5.Number of expected 1016 job seekers',
    color: '#5cb85c',
    eventType: 'J',
    start: '/Date(1596133800000)/',
    end: '/Date(1596652140000)/',
    regStDate: '/Date(1595788200000)/',
    regEnDate: '/Date(1596047340000)/',
    eventMode: true,
    OrganisedBy: 'Shrawasti, Uttar Pradesh',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames:
      'SREE KARAYIL CHITS (INDIA) LIMITED, JYOTI PLACEMENTS SERVICE',
    id: 'CMP-06703-T2D8P6',
    title:
      'JF-AS-Online Nagaon MCC at Assam, Nagaon from 1st Aug\u002720 to 05th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '1',
    totalJobseekers: '18',
    totalParticipants: '19',
    totalJobs: '2',
    eventDesc:
      'FLORTON INFRASTRUCTURE PVT. LTD is recruiting through JYOTI PLACEMENTS SERVICE/SREE KARAYIL CHITS (INDIA) LIMITED for the Billing and Cashier from MCC Nagaon. Expected jobseekers for the post is 50 to 70.',
    color: '#5cb85c',
    eventType: 'J',
    start: '/Date(1596220200000)/',
    end: '/Date(1596652140000)/',
    regStDate: '/Date(1596047400000)/',
    regEnDate: '/Date(1596133740000)/',
    eventMode: false,
    OrganisedBy: 'Nagaon, Assam',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: 'SHADOWFAX TECHNOLOGY PVT LTD',
    id: 'CMP-06718-S1P3W7',
    title:
      'JF-GJ-Online Job Fair Rajkot on NCS Portal from 3rd Aug\u002720 to 5th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'Post Name : Delivery Partner (Boy) Age : 18+ Qualification : 10th Pass \u0026 Driving Licence',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596393000000)/',
    end: '/Date(1596652140000)/',
    regStDate: '/Date(1596133800000)/',
    regEnDate: '/Date(1596306540000)/',
    eventMode: true,
    OrganisedBy: 'Rajkot, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: '1. SHIV SHAKTI BIO TECHNOLOGIES- AHMEDBAD',
    id: 'CMP-06717-D5M2P2',
    title:
      'JF-GJ-Online ONLINE JOB FAIR on NCS Portal from 4th Aug\u002720 to 6th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '1',
    totalJobseekers: '0',
    totalParticipants: '1',
    totalJobs: '28',
    eventDesc: 'SSC, HSC AND GRADUTION STUDENTS CAN APPLY FOR THIS JOB',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596479400000)/',
    end: '/Date(1596738540000)/',
    regStDate: '/Date(1596047400000)/',
    regEnDate: '/Date(1596392940000)/',
    eventMode: true,
    OrganisedBy: 'Surendranagar, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: '1. SKH-Y-TECH LTD( KRISHNA MARUTI GROUP)- BECHRAJI .',
    id: 'CMP-06720-Q1P8Z5',
    title:
      'JF-GJ-Online ONLINE JOBFAIR on NCS Portal from 4th Aug\u002720 to 6th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '1',
    totalJobseekers: '0',
    totalParticipants: '1',
    totalJobs: '23',
    eventDesc: 'ONLY ITI (ANY TRADE) STUDENTS CAN APPLY FOR THIS JOB',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596479400000)/',
    end: '/Date(1596738540000)/',
    regStDate: '/Date(1596047400000)/',
    regEnDate: '/Date(1596392940000)/',
    eventMode: true,
    OrganisedBy: 'Surendranagar, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: 'Welspun India Anjar Kutch, CSC E Governance',
    id: 'CMP-06722-Q7M2Y2',
    title: 'JF-GJ-Online Virtual JF on NCS Portal on 4th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'The recruitment fair will be online and the candidates will be telephonically interviewed by the employer which all the candidates should take note of.',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596479400000)/',
    end: '/Date(1596565740000)/',
    regStDate: '/Date(1596306600000)/',
    regEnDate: '/Date(1596392940000)/',
    eventMode: true,
    OrganisedBy: 'Jamnagar, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: '1) VRUNDAVAN PLACEMENT- RAJKOT',
    id: 'CMP-06733-W2H1H5',
    title:
      'JF-GJ-Online JOB PLACEMENT on NCS Portal from 4th Aug\u002720 to 6th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.\r\n',
    typeOfEvent: 'Seminar',
    totalEmployers: '1',
    totalJobseekers: '0',
    totalParticipants: '1',
    totalJobs: '28',
    eventDesc:
      'MODEL CAREER CENTER- DEVBHUMI DWARKA AT KHAMBHALIYA ORGANIZATION ONLINE JOB FAIR Post Name : HELPER : 18+ Qualification : SSC/HSC',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596479400000)/',
    end: '/Date(1596738540000)/',
    regStDate: '/Date(1596133800000)/',
    regEnDate: '/Date(1596392940000)/',
    eventMode: true,
    OrganisedBy: 'Devbhumi Dwarka, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: 'Only One i.e. Aadhya Placements',
    id: 'CMP-06744-J7M0C1',
    title:
      'JF-GJ-Online Job Drive on NCS Portal from 4th Aug\u002720 to 5th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'Aadhya Placements hiring for Client, Total Vacancies: 5, Job Role: Plant Operators; Education: Diploma in Chemical/Graduation in Chemistry; Age: 20-25 years, Fresher or experience candidate needed. Salary: Rs 10,000/month onwards',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596479400000)/',
    end: '/Date(1596652140000)/',
    regStDate: '/Date(1596306600000)/',
    regEnDate: '/Date(1596392940000)/',
    eventMode: true,
    OrganisedBy: 'Bharuch, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: 'Exide life insurance',
    id: 'CMP-06728-T0L3H9',
    title: 'JF-RJ-Placement drive at Rajasthan, Kota on 4th Aug\u002720',
    venue:
      'Exide life insurance,kota near Aerodrome circle shopping center ,Kota (Rajasthan)',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'Expected vacancies- 15 Qualification-Graduation Expected company-1',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596511800000)/',
    end: '/Date(1596533400000)/',
    regStDate: '/Date(1596425400000)/',
    regEnDate: '/Date(1596508200000)/',
    eventMode: false,
    OrganisedBy: 'Kota, Rajasthan',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: 'jai shree bioplantech pvt ltd udaipur',
    id: 'CMP-06707-N0K9M8',
    title:
      'JF-RJ-Online sales job drive on NCS Portal from 5th Aug\u002720 to 7th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'name of the company -jai shree bioplantech pvt ltd udaipur name\u0026 number of post-20 age -18-35 qualification- minimum 10 pass',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596565800000)/',
    end: '/Date(1596824940000)/',
    regStDate: '/Date(1595788200000)/',
    regEnDate: '/Date(1596479340000)/',
    eventMode: true,
    OrganisedBy: 'Bharatpur, Rajasthan',
  },
  {
    sCRMEmpCount: '6',
    sCRMEmpNames:
      'Sivashakthi Bio Technologies Ltd, SCORPIX INDIA, KALYANI SOLAR POWER, Shree Sai services, Vinuthna Fertilizers, XZENT AQUA PVT LTD',
    id: 'CMP-06740-S2C5K9',
    title:
      'JF-UP-Online MCC Sitapur at Uttar Pradesh, Sitapur on 05th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '1',
    totalJobseekers: '0',
    totalParticipants: '1',
    totalJobs: '4',
    eventDesc:
      'MCC Sitapur is organising Online Job Fair on 5th August, 2020. For any query please contact Sh. Amit Kumar District Employment Officer, Sitapur 6393040279',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596565800000)/',
    end: '/Date(1596652140000)/',
    regStDate: '/Date(1596220200000)/',
    regEnDate: '/Date(1596479340000)/',
    eventMode: true,
    OrganisedBy: 'Sitapur, Uttar Pradesh',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: '1 aadhya placement',
    id: 'CMP-06745-D0H6K6',
    title: 'JF-GJ-Online JobDrive at Gujarat, Bharuch on 5th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'Aadhya Placements hiring for Client, Total Vacancies: 5, Job Role: Plant Operators; Education: Diploma in Chemical/Graduation in Chemistry; Age: 20-25 years, Fresher or experience candidate needed. Salary: Rs 10,000/month onwards',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596605400000)/',
    end: '/Date(1596630600000)/',
    regStDate: '/Date(1596380400000)/',
    regEnDate: '/Date(1596598200000)/',
    eventMode: false,
    OrganisedBy: 'Bharuch, Gujarat',
  },
  {
    sCRMEmpCount: '2',
    sCRMEmpNames: '1.KRISHNA MARUTI GROUP , 2.LIC AMRELI',
    id: 'CMP-06719-S0Y3S0',
    title:
      'JF-GJ-Online JOBFAIR AMRELI on NCS Portal from 6th Aug\u002720 to 13th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc: 'No Description',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596652200000)/',
    end: '/Date(1597343340000)/',
    regStDate: '/Date(1596047400000)/',
    regEnDate: '/Date(1596565740000)/',
    eventMode: true,
    OrganisedBy: 'Amreli, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: '(1) MOTHERSON SUMI SYSTEM LTD-AHEMDABAD',
    id: 'CMP-06732-X5G0V3',
    title:
      'JF-GJ-E Job Fair at Gujarat, Botad from 6th Aug\u002720 to 8th Aug\u002720',
    venue: 'E-Job Fair',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'E-Job Fair Organized By District Employment Exchange \u0026 Model Career Centre-Botad through Digital Platform E-Job Fair Date:06/08/2020 to 08/08/2020 for More Information Contact us for E-Job Fair regarding Details on Office Tele Phone -02849 271315',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596691800000)/',
    end: '/Date(1596886200000)/',
    regStDate: '/Date(1596133800000)/',
    regEnDate: '/Date(1596565800000)/',
    eventMode: false,
    OrganisedBy: 'Botad, Gujarat',
  },
  {
    sCRMEmpCount: '2',
    sCRMEmpNames: '1- Instakart Service pvt ltd, 2 -Essal Propek',
    id: 'CMP-06723-W3K3Y0',
    title: 'JF-GJ-Online Virtual JF on NCS Portal on 7th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'The recruitment fair will be online and the candidates will be telephonically interviewed by the employer which all the candidates should take note of.',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596738600000)/',
    end: '/Date(1596824940000)/',
    regStDate: '/Date(1596565800000)/',
    regEnDate: '/Date(1596652140000)/',
    eventMode: true,
    OrganisedBy: 'Jamnagar, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: '1',
    id: 'CMP-06734-P3Q5P9',
    title: 'JF-GJ-Online INDUSTRIAL JF on NCS Portal on 7th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc: 'No Description',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596738600000)/',
    end: '/Date(1596824940000)/',
    regStDate: '/Date(1596133800000)/',
    regEnDate: '/Date(1596652140000)/',
    eventMode: true,
    OrganisedBy: 'Porbandar, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: 'Wellness Forever Medicare Pvt Ltd, Silver Leaf Corporation',
    id: 'CMP-06743-S2N1X8',
    title:
      'JF-MH-Online JF at Thane@Mah on NCS Portal from 9th Aug\u002720 to 15th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'Openings for SSC/HSC \u0026 B. Pharma/D.Pharma candidates all over Mumbai \u0026 Maharashtra',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596911400000)/',
    end: '/Date(1597516140000)/',
    regStDate: '/Date(1596393000000)/',
    regEnDate: '/Date(1596824940000)/',
    eventMode: true,
    OrganisedBy: 'Thane, Maharashtra',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames:
      '1-Shivashakti Bio Technologies 2-Xzent Aqua pvt ltd 3-Pukhraj Helth Care Pvt. Ltd 4- kalyani solar power 5-scorpix India 6-magadha Agro Tech 7- Rohit Hybrid seeds pvt ltd Ghazipur 8-Vinuthna Fertilizerss',
    id: 'CMP-06713-N8S8T4',
    title: 'JF-UP-Online Online Job Fair on NCS Portal on 10th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '1',
    totalJobseekers: '0',
    totalParticipants: '1',
    totalJobs: '4',
    eventDesc:
      '1-Shivashakti Bio Technologies 2-Xzent Aqua pvt ltd 3-Pukhraj Helth Care Pvt. Ltd 4- kalyani solar power 5-scorpix India 6-magadha Agro Tech 7- Rohit Hybrid seeds pvt ltd Ghazipur 8-Vinuthna Fertilizerss',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1596997800000)/',
    end: '/Date(1597084140000)/',
    regStDate: '/Date(1595961000000)/',
    regEnDate: '/Date(1596911340000)/',
    eventMode: true,
    OrganisedBy: 'Ghazipur, Uttar Pradesh',
  },
  {
    sCRMEmpCount: '10',
    sCRMEmpNames:
      '. SIS SECURITY INDIA PVT. LTD. DEHRADUN, 2. SHIVSHAKTI BIO TECHNOLOGY LIMITED, 3. BABA SHIV BIO TECHNOLOGY PLANT PVT. LTD., 4. KALYANI SOLAR POWER, 5. CARTHERO TECHNOLOGY PVT. LTD., 6. LIC OF INDIA, TUNDLA BRANCH, 7. LIC OF INDIA, FIROZABAD BRANCH, 8. YASHWANT RAO TECHNICAL AND TRAINING FOUNDATION, 9. SHUBH PLANTIC PVT. LTD. AGRA, 10. LIC OF INDIA, SHIKOHABAD',
    id: 'CMP-06721-T3H8Y3',
    title: 'JF-UP-Online ONLINE JOB FAIR on NCS Portal on 11th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'Number of expected companies- 15 List of prominent companies expected-15 Companies from which sector are expected to have maximum presence- AGRICULTURE, BIOTECH, FERTILIZERS Number of expected vacancies- 1500+ Number of expected job-seekers- 2000+',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1597084200000)/',
    end: '/Date(1597170540000)/',
    regStDate: '/Date(1596911400000)/',
    regEnDate: '/Date(1596997740000)/',
    eventMode: true,
    OrganisedBy: 'Firozabad, Uttar Pradesh',
  },
  {
    sCRMEmpCount: '3',
    sCRMEmpNames: '1-Bajaj Aliyanz, 2- Zomato Jamnagar, 3- Toshree Industries',
    id: 'CMP-06724-N4T0D2',
    title: 'JF-GJ-Online Virtual  JF on NCS Portal on 11th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc:
      'The recruitment fair will be online and the candidates will be telephonically interviewed by the employer which all the candidates should take note of.',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1597084200000)/',
    end: '/Date(1597170540000)/',
    regStDate: '/Date(1596911400000)/',
    regEnDate: '/Date(1596997740000)/',
    eventMode: true,
    OrganisedBy: 'Jamnagar, Gujarat',
  },
  {
    sCRMEmpCount: '2',
    sCRMEmpNames:
      '1.BROTHERS CONSALTANCY- GANDHINAGAR , 2.SHIV SHAKTI AUTO CENTRE- SURENDRANAGAR',
    id: 'CMP-06735-D0R3H7',
    title:
      'JF-GJ-Online online jobfair on NCS Portal from 12th Aug\u002720 to 14th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc: 'No Description',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1597170600000)/',
    end: '/Date(1597429740000)/',
    regStDate: '/Date(1596565800000)/',
    regEnDate: '/Date(1597084140000)/',
    eventMode: true,
    OrganisedBy: 'Surendranagar, Gujarat',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: '--',
    id: 'CMP-06739-T8Z0F0',
    title: 'JF-UP-Online Rojgar mela on NCS Portal on 14th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '1',
    totalJobseekers: '0',
    totalParticipants: '1',
    totalJobs: '4',
    eventDesc: 'No Description',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1597343400000)/',
    end: '/Date(1597429740000)/',
    regStDate: '/Date(1596220200000)/',
    regEnDate: '/Date(1597256940000)/',
    eventMode: true,
    OrganisedBy: 'Pratapgarh, Uttar Pradesh',
  },
  {
    sCRMEmpCount: '1',
    sCRMEmpNames: '1',
    id: 'CMP-06742-B3R1J2',
    title: 'JF-GJ-Online INDUSTRIAL JF on NCS Portal on 14th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc: 'No Description',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1597343400000)/',
    end: '/Date(1597429740000)/',
    regStDate: '/Date(1596220200000)/',
    regEnDate: '/Date(1597256940000)/',
    eventMode: true,
    OrganisedBy: 'Porbandar, Gujarat',
  },
  {
    sCRMEmpCount: '2',
    sCRMEmpNames:
      '1.SUZUKI PVT LTD- HANSALPUR , 2.REALIBLE FIRST PVT LTD- AHMEDBAD',
    id: 'CMP-06736-Y0C3P7',
    title:
      'JF-GJ-Online online jobfair on NCS Portal from 15th Aug\u002720 to 20th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc: 'No Description',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1597429800000)/',
    end: '/Date(1597948140000)/',
    regStDate: '/Date(1597084200000)/',
    regEnDate: '/Date(1597343340000)/',
    eventMode: true,
    OrganisedBy: 'Surendranagar, Gujarat',
  },
  {
    sCRMEmpCount: '2',
    sCRMEmpNames:
      '1. MARITU NETWORK PVT LTD-RAJKOT , 2.SHIV SHAKTI BIO-TECHNOLOGIES LTD- AHMEDBAD',
    id: 'CMP-06737-K9B4T3',
    title:
      'JF-GJ-Online online jobfair on NCS Portal from 23rd Aug\u002720 to 27th Aug\u002720',
    venue:
      'In view of the current lockdown situation, all NCS Job Fairs will be conducted online on NCS portal. Please participate using the below proceed button to receive interview calls.',
    typeOfEvent: 'Seminar',
    totalEmployers: '0',
    totalJobseekers: '0',
    totalParticipants: '0',
    totalJobs: '0',
    eventDesc: 'No Description',
    color: '#5bc0de',
    eventType: 'J',
    start: '/Date(1598121000000)/',
    end: '/Date(1598552940000)/',
    regStDate: '/Date(1597775400000)/',
    regEnDate: '/Date(1598034540000)/',
    eventMode: true,
    OrganisedBy: 'Surendranagar, Gujarat',
  },
];
